POST https://fist-step-nodejs.onrender.com/videos
Content-Type: application/json

{
  "title": "Video 10",
  "description": "This is the video node",
  "duration": 60
}

###

GET https://fist-step-nodejs.onrender.com/videos

###

PUT https://fist-step-nodejs.onrender.com/videos/a54c3f2d-0d75-42d6-8013-d3462e6e5b4f
Content-Type: application/json

{
  "title": "Video 5",
  "description": "This videos as update",
  "duration": 180
}

###

DELETE https://fist-step-nodejs.onrender.com/videos/a54c3f2d-0d75-42d6-8013-d3462e6e5b4f


